{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Speedtest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_upload_bytes_per_seconds*8",
     "legendFormat": "Up        ({{server_id}}: {{server_name}})"
    },
    {
     "expr": "speedtest_download_bytes_per_seconds*8",
     "legendFormat": "Down ({{server_id}}: {{server_name}})"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(speedtest_latency_milliseconds)",
     "legendFormat": "Latency"
    },
    {
     "expr": "avg(speedtest_jittter_milliseconds)",
     "legendFormat": "Jitter"
    },
    {
     "expr": "avg(speedtest_upload_latency_milliseconds)",
     "legendFormat": "Upload latency"
    },
    {
     "expr": "avg(speedtest_upload_jitter_milliseconds)",
     "legendFormat": "Upload jitter"
    },
    {
     "expr": "avg(speedtest_download_latency_milliseconds)",
     "legendFormat": "Download latency"
    },
    {
     "expr": "avg(speedtest_download_jitter_milliseconds)",
     "legendFormat": "Download jitter"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "speedtest_packet_loss_percentage",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  { "title": "Service reachability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "TCP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "sum(probe_duration_seconds{instance!~\"http.*\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Turing2 net stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 48 },
   "targets": [
    {
     "expr": "node_network_receive_errs_total{device=\"eth0\"}",
     "legendFormat": "RC (errs)"
    },
    {
     "expr": "node_network_receive_drop_total{device=\"eth0\"}",
     "legendFormat": "RC (drops)"
    },
    {
     "expr": "node_network_transmit_errs_total{device=\"eth0\"}",
     "legendFormat": "TX (errs)"
    },
    {
     "expr": "node_network_transmit_drops_total{device=\"eth0\"}",
     "legendFormat": "TX (drops)"
    }
   ]
  }
 ]
}